### ISSUE TITLE
Research

### ISSUE THREAD

**Issue by Johnson-OpNet** [wannnn/BunnyWallet#1]
Library : 
web3j => https://github.com/web3j/web3j/
bitcoinj => https://github.com/bitcoinj/bitcoinj
KEthereum => https://github.com/komputing/KEthereum

**Comment by Johnson-OpNet** [comment]
2 options to generate wallet :
* KEthereum (Kotlin)
* web3j + bitcoinj

**Comment by wannnn** [comment]
Decided to use Web3j 👍
